add_repositories("liteldev-repo https://github.com/LiteLDev/xmake-repo.git")
add_requires("preloader v1.3.0")

target("plugin")
    add_files("src/**.cpp")
    set_symbols("debug")
    add_includedirs("include")
    add_rules("mode.debug", "mode.release")
    set_arch("x64")
    set_kind("shared")
    set_languages("cxx20")
    set_plat("windows")
    set_toolchains("msvc")
    add_packages("preloader")
    add_defines("CC_EXPORT")
    add_shflags("/DELAYLOAD:bedrock_server.dll")
